### ISSUE TITLE
Default port in the svc yaml for UI

### ISSUE THREAD

**Issue by jian-he** [kubedl-io/morphling#28]
the default port for ui in service.yaml and service_lb.yaml is 80, should it be the same as targetPort 9091 for convenince ?

```yaml
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      name: ui
      targetPort: 9091
```
